title: Aayushi Singh
logo: /assets/img/logo.png
description: Curious engineer exploring systems, performance, and elegant problem solving and seeing this world from lens of poetry
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
